spring:
  application:
    name: project-service
  ssl:
    enabled: true
    key-alias: "my-cert"
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: ${GP_PROJECTSERVICE_KEYSTORE_PASSWORD:1PwCgNAb}
    bundle:
      jks:
        keycloak:
          key:
            alias: "my-cert"
          keystore:
            type: PKCS12
            location: classpath:certificate.p12
            password: ${GP_PROJECTSERVICE_KEYSTORE_PASSWORD:1PwCgNAb}

  kafka:
    notification:
      topic: notification-topic
      group: notification-group
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}

  datasource:
    url: '${DB_URL:jdbc:postgresql://localhost:5432/projectservicedb}'
    username: '${DB_USER:projectservice}'
    password: '${DB_PASSWORD:12345}'
    driverClassName: org.postgresql.Driver

  liquibase:
    user: '${DB_USER:projectservice}'
    password: '${DB_PASSWORD:12345}'
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false


  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087

grpc:
  server:
    port: 9090

services:
  auth-service:
    addr: ${AUTH_SERVICE_URL:https://localhost:8088}
  chat-service:
    create-chat-url: "http://localhost:8084/api/chats"
logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG


invitation-service:
  user-already-invited-error-message: "Приглашение пользователю уже было отправлено"
  create-invitation: "http://localhost:8082/api/invitations"

