spring:
  application:
    name: project-service

  kafka:
    notification:
      topic: notification-topic
      group: notification-group
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}

  datasource:
    url: '${DB_URL:jdbc:postgresql://localhost:5432/projectservicedb}'
    username: '${DB_USER:projectservice}'
    password: '${DB_PASSWORD:12345}'
    driverClassName: org.postgresql.Driver

  liquibase:
    user: '${DB_USER:projectservice}'
    password: '${DB_PASSWORD:12345}'
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  
  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087

grpc:
  server:
    port: 9090

services:
  auth-service:
    addr: ${AUTH_SERVICE_URL:http://localhost:8088}
logging:
  level:
    root: 'INFO'
    # org.springframework.web: 'DEBUG'
    # ru.itpark.projectservice: 'DEBUG'