spring:
  application:
    name: invitation-service
  ssl:
    enabled: true
    key-alias: "my-cert"
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: ${GP_INVITATIONSERVICE_KEYSTORE_PASSWORD:1PwCgNAb}

  datasource:
    url: '${GP_INVITATIONSERVICE_DB_URL:jdbc:postgresql://localhost:5432/invitationservicedb}'
    username: '${GP_INVITATIONSERVICE_DB_USERNAME:invitationservice}'
    password: '${GP_INVITATIONSERVICE_DB_PASSWORD:12345}'
    driverClassName: org.postgresql.Driver

  liquibase:
    user: '${GP_INVITATIONSERVICE_DB_USERNAME:invitationservice}'
    password: '${GP_INVITATIONSERVICE_DB_PASSWORD:12345}'
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082