version: '3.8'

services:
  document-service:
    build:
      context: .
    ports:
      - 8083:8083
    environment:
      - GP_DOCUMENT_SERVICE_KEYSTORE_PASSWORD=1PwCgNAb
      - GP_DOCUMENT_SERVICE_DB_URL=jdbc:postgresql://localhost:5432/invitationservicedb
      - GP_DOCUMENT_SERVICE_DB_USERNAME=invitationservice
      - GP_DOCUMENT_SERVICE_DB_PASSWORD=12345
    depends_on:
      - collaborative-project-postgres-db
    networks:
      backend: {}

  liquibase-document:
    image: liquibase/liquibase:alpine
    working_dir: /liquibase/changelog
    depends_on:
      - collaborative-project-postgres-db
    entrypoint: [ "sh", "-c", "sleep 30 && echo \"DB_URL=$LIQUIBASE_COMMAND_URL\" && echo \"DB_USER=${LIQUIBASE_COMMAND_USERNAME}\" && echo \"DB_PASSWORD=${LIQUIBASE_COMMAND_PASSWORD}\" && liquibase --url=${LIQUIBASE_COMMAND_URL} --changeLogFile=${LIQUIBASE_COMMAND_CHANGELOG_FILE} --username=${LIQUIBASE_COMMAND_USERNAME} --password=${LIQUIBASE_COMMAND_PASSWORD} --log-level=INFO update" ]
    environment:
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changelog-master.yaml
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/documentservicedb
      - LIQUIBASE_COMMAND_USERNAME=documentservice
      - LIQUIBASE_COMMAND_PASSWORD=12345
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    networks:
      backend: