server:
  port: 8089

spring:
  application:
    name: notification-service
  datasource:
    url: ${GP_NOTIFICATION_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/notificationservicedb}
    username: notificationservice
    password: '12345'
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: notification-group

notification:
  emails:
    server: ${GP_NOTIFICATION_SERVICE_SERVER}
    password: ${GP_NOTIFICATIONSERVICE_SERVER_PASS}