server:
  port: 8089

spring:
  application:
    name: notification-service
  datasource:
    url: ${GP_NOTIFICATION_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/notificationservicedb}
    username: notificationservice
    password: '12345'
    driver-class-name: org.postgresql.Driver