server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: certificate.p12
    key-store-password: 1PwCgNAb

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: 'my-group'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.dppmai.ru/realms/group-1
          jwk-uri: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/certs
  liquibase:
    user: authservice
    password: 12345
    change-log: 'classpath:db/changelog/db-init.yaml'
#    change-log: '${project.basedir}/src/main/resources/db/changelog/db-init.yaml'
  datasource:
    url: ${SPRING_DATASOURCE_URL}
#    url: jdbc:postgresql://localhost:5432/authservicedb
    username: authservice
    password: 12345
    driverClassName: org.postgresql.Driver

keycloak:
  serverUrl: https://lemur-7.cloud-iam.com
  realm: lessons
  clientId: auth-service
  username: admin
  password: HVG-Rqf-5PV-Lp6
  realmName: lessons
  loginUrl: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/token
  client-secret: "${client-secret}"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} %M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n"
  file:
    name: log.txt
  level:
    root: info
