server:
  port: 8088
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: 1PwCgNAb

spring:
  ssl:
    bundle:
      jks:
        keycloak:
          key:
            alias: "my-cert"
          keystore:
            type: PKCS12
            location: classpath:certificate.p12
            password: ${GP_AUTHSERVICE_KEYSTORE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-7.cloud-iam.com/auth/realms/grad-project
          jwk-uri: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/certs
  liquibase:
    enabled: false
    user: authservice
    password: 12345
    change-log: 'db/changelog/db.changelog-master.yaml'
#    change-log: '${project.basedir}/src/main/resources/db/changelog/db.changelog-master.yaml'
  datasource:
    url: ${GP_AUTHSERVICE_DB_URL:jdbc:postgresql://localhost:5432/authservicedb}
    username: authservice
    password: 12345
    driverClassName: org.postgresql.Driver

keycloak:
  serverUrl: https://lemur-7.cloud-iam.com
  realm: grad-project
  clientId: auth-service
  username: admin
  password: nvwS6vK#IaE@Ds4RveKs
  realmName: grad-project
  loginUrl: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/token
  client-secret: "${GP_AUTHSERVICE_CLIENT_SECRET}"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} %M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n"
  file:
    name: log.txt
  level:
    root: info

grpc:
  client:
    GLOBAL:
      address: static://project-service:9090
      negotiation-type: plaintext
