server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: certificate.p12
    key-store-password: 1PwCgNAb

spring:
  ssl:
    bundle:
      jks:
        keycloak:
          key:
            alias: "my-cert"
          keystore:
            type: PKCS12
            location: classpath:certificate.p12
            password: ${GP_AUTHSERVICE_KEYSTORE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-7.cloud-iam.com/auth/realms/grad-project
          jwk-uri: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/certs
  liquibase:
    user: authservice
    password: ${GP_AUTHSERVICE_DB_PASSWORD}
    change-log: 'classpath:db/changelog/db-init.yaml'
  datasource:
    url: jdbc:postgresql://localhost:5432/authservicedb
    username: authservice
    password: ${GP_AUTHSERVICE_DB_PASSWORD}
    driverClassName: org.postgresql.Driver

keycloak:
  serverUrl: https://lemur-7.cloud-iam.com
  realm: grad-project
  clientId: auth-service
  username: admin
  password: ${GP_KEYCLOAK_ADMIN_PASSWORD}
  realmName: grad-project
  loginUrl: https://lemur-7.cloud-iam.com/auth/realms/grad-project/protocol/openid-connect/token
  client-secret: ${GP_AUTHSERVICE_CLIENT_SECRET}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} %M - %msg%n"
#     file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n"
#  file:
#    name: log.txt
  level:
    root: info

org:
  springframework:
    test:
      context:
        cache: DEBUG