server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: backend/auth-service/certificate.p12
    key-store-password: 1PwCgNAb

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.dppmai.ru/realms/lessons
          jwk-uri: https://auth.dppmai.ru/realms/lessons/protocol/openid-connect/certs
  liquibase:
    user: authservice
    password: 12345
    change-log: 'classpath:db/changelog/db-init.yaml'
  datasource:
    url: "jdbc:postgresql://localhost:5432/authservicedb"
    username: authservice
    password: 12345

keycloak:
  serverUrl: https://auth.dppmai.ru
  realm: lessons
  clientId: admin-cli
  username: admin
  password: HVG-Rqf-5PV-Lp6
  realmName: lessons


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} %M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n"
  file:
    name: log.txt
  level.root: info
