spring:
  application:
    name: document-service
  datasource:
    url: ${GP_DOCUMENT_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/documentservicedb}
    username: ${GP_DOCUMENT_SERVICE_DB_USERNAME:documentservice}
    password: ${GP_DOCUMENT_SERVICE_DB_PASSWORD:12345}
    driverClassName: org.postgresql.Driver

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: grad-project
server:
  port: 8083