version: '3.8'

services:
  notification-service:
    restart: always
    build:
      context: .
      args:
        - DB_NAME=notificationservicedb
        - DB_PORT=5432
        - DB_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/notificationservicedb
        - DB_USER=notificationservice
        - DB_PASSWORD=12345
    ports:
      - 8089:8089
    environment:
      - DB_NAME=notificationservicedb
      - DB_PORT=5432
      - DB_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/notificationservicedb
      - DB_USER=notificationservice
      - DB_PASSWORD=12345
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - GP_NOTIFICATION_SERVICE_DB_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/notificationservicedb
    depends_on:
      - collaborative-project-postgres-db
      - kafka
      - zookeeper
    networks:
      backend: {}

  liquibase-notification:
    image: liquibase/liquibase:alpine
    working_dir: /liquibase/changelog
    depends_on:
      - collaborative-project-postgres-db
    entrypoint: [ "sh", "-c", "sleep 30 && echo \"DB_URL=$LIQUIBASE_COMMAND_URL\" && echo \"DB_USER=${LIQUIBASE_COMMAND_USERNAME}\" && echo \"DB_PASSWORD=${LIQUIBASE_COMMAND_PASSWORD}\" && liquibase --url=${LIQUIBASE_COMMAND_URL} --changeLogFile=${LIQUIBASE_COMMAND_CHANGELOG_FILE} --username=${LIQUIBASE_COMMAND_USERNAME} --password=${LIQUIBASE_COMMAND_PASSWORD} --log-level=INFO update" ]
    environment:
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changelog-master.yaml
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/notificationservicedb
      - LIQUIBASE_COMMAND_USERNAME=notificationservice
      - LIQUIBASE_COMMAND_PASSWORD=12345
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    networks:
      backend: