version: '3.8'

services:
  chat-service:
    build:
      context: .
      network: host
    ports:
      - 8084:8084
    environment:
      - GP_CHATSERVICE_DB_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/chatservicedb
      - GP_CHATSERVICE_DB_USERNAME=chatservice
      - GP_CHATSERVICE_DB_PASSWORD=12345
    depends_on:
      - collaborative-project-postgres-db
      - kafka
      - zookeeper
    networks:
      backend: {}

  liquibase-chat:
    image: liquibase/liquibase:alpine
    working_dir: /liquibase/changelog
    depends_on:
      - collaborative-project-postgres-db
    entrypoint: [ "sh", "-c", "sleep 30 && echo \"DB_URL=$LIQUIBASE_COMMAND_URL\" && echo \"DB_USER=${LIQUIBASE_COMMAND_USERNAME}\" && echo \"DB_PASSWORD=${LIQUIBASE_COMMAND_PASSWORD}\" && liquibase --url=${LIQUIBASE_COMMAND_URL} --changeLogFile=${LIQUIBASE_COMMAND_CHANGELOG_FILE} --username=${LIQUIBASE_COMMAND_USERNAME} --password=${LIQUIBASE_COMMAND_PASSWORD} --log-level=INFO update" ]
#    entrypoint: [ "liquibase", "update" ]
#    command: ["sleep 5"]
    environment:
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changelog-master.yaml
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://collaborative-project-postgres-db:5432/chatservicedb
      - LIQUIBASE_COMMAND_USERNAME=chatservice
      - LIQUIBASE_COMMAND_PASSWORD=12345
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    networks:
      backend: