services:
  minio:
    image: minio/minio
    container_name: minio-minio
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-sS', 'http://localhost:9000/minio/health/ready']
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - minio-net

networks:
  minio-net: {}

volumes:
  minio_data: