spring:
  application:
    name: chat-service
  datasource:
    url: ${GP_CHATSERVICE_DB_URL:jdbc:postgresql://localhost:5432/chatservicedb}
    username: ${GP_CHATSERVICE_DB_USERNAME:chatservice}
    password: ${GP_CHATSERVICE_DB_PASSWORD:12345}
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8084
