version: '3'
services:
  maven:
    restart: always
    ports:
      - "8088:8088"
    image: maven:3.8.3-openjdk-17
    command: mvn clean package spring-boot:run
#    command: mvn package
    volumes:
      - .:/usr/src/mymaven
      - $HOME/.m2:/root/.m2
#      - ./target:/usr/src/mymaven/target
    working_dir: /usr/src/mymaven
    stdin_open: true
    tty: true
    environment:
      - GP_AUTHSERVICE_DB_URL=jdbc:postgresql://collaborative-project-postgres-db/authservicedb
      - GP_AUTHSERVICE_DB_USERNAME=authservice
      - GP_AUTHSERVICE_DB_PASSWORD=12345
      - GP_AUTHSERVICE_KEYSTORE_PASSWORD=1PwCgNAb
      - GP_KEYCLOAK_ADMIN_PASSWORD=nvwS6vK#IaE@Ds4RveKs
      - GP_AUTHSERVICE_CLIENT_SECRET=7TCb2UhbgVpyh186oC6VMe9srakq16Bp
      - KEYCLOAK_DEAD=0
    depends_on:
      - collaborative-project-postgres-db
      - kafka
    networks:
      backend: {}

# version: '3'
# services:
  # maven:
    # image: maven:3.8.3-openjdk-17
    # command: mvn spring-boot:run
    # volumes:
      # - .:/usr/src/mymaven
      # - $HOME/.m2:/root/.m2
      # - ./target:/usr/src/mymaven/target
    # working_dir: /usr/src/mymaven
    # stdin_open: true
    # tty: true
  
  # postgresql:
    # image: postgres:14.2
    # environment:
      # - POSTGRES_DB=authservicedb
      # - POSTGRES_USER=authservice
      # - POSTGRES_PASSWORD=12345
    # volumes:
      # - postgres-data:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"
    
# volumes:
  # postgres-data: {}
  # postgres-data: {}